//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public long UserId { get; set; }
        public string UserMobile { get; set; }
        public string UserPass { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string ProfilImage { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string ResetPassword { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CounterID { get; set; }
    }
}
