//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenRegistration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Age { get; set; }
        public int CounterNumberID { get; set; }
        public int DepartmentID { get; set; }
        public string Gender { get; set; }
        public string TokenNumber { get; set; }
        public string Payment { get; set; }
        public System.DateTime Date { get; set; }
    }
}
